### ISSUE TITLE
Console Error Logs in CI Jest Test

### ISSUE THREAD

**Issue by Sebastian-Haehnlein** [intershop/intershop-pwa#95]
**Actual Behavior**

`user.effects.spec.ts` log some errors to console.error  
"Unhandled Promise rejection: Cannot match any routes. URL Segment: 'account/profile'"  
looks like logging without throwing an error

**Expected Behavior**
 
clean output for ci
 

**Steps to Reproduce the Bug**

1. run jest tests (npm t)

**Additional Context, like Screenshots, Log File Snippets etc.**

```
console.error node_modules/zone.js/dist/zone.js:703
      Unhandled Promise rejection: Cannot match any routes. URL Segment: 'account/profile' ; Zone: ProxyZone ; Task: Promise.then ; Value: Error: Cannot match any routes. URL Segment: 'account/profile'
          at ApplyRedirects.noMatchError (/home/runner/work/intershop-pwa/packages/router/src/apply_redirects.ts:112:12)
          at CatchSubscriber.selector (/home/runner/work/intershop-pwa/packages/router/src/apply_redirects.ts:89:20)
          at CatchSubscriber.Object.<anonymous>.CatchSubscriber.error (/home/runner/work/intershop-pwa/intershop-pwa/node_modules/rxjs/src/internal/operators/catchError.ts:132:23)
          at MapSubscriber.Object.<anonymous>.Subscriber._error (/home/runner/work/intershop-pwa/intershop-pwa/node_modules/rxjs/src/internal/Subscriber.ts:143:22)
          at MapSubscriber.Object.<anonymous>.Subscriber.error (/home/runner/work/intershop-pwa/intershop-pwa/node_modules/rxjs/src/internal/Subscriber.ts:113:12)
          at MapSubscriber.Object.<anonymous>.Subscriber._error (/home/runner/work/intershop-pwa/intershop-pwa/node_modules/rxjs/src/internal/Subscriber.ts:143:22)
          at MapSubscriber.Object.<anonymous>.Subscriber.error (/home/runner/work/intershop-pwa/intershop-pwa/node_modules/rxjs/src/internal/Subscriber.ts:113:12)
          at MapSubscriber.Object.<anonymous>.Subscriber._error (/home/runner/work/intershop-pwa/intershop-pwa/node_modules/rxjs/src/internal/Subscriber.ts:143:22)
          at MapSubscriber.Object.<anonymous>.Subscriber.error (/home/runner/work/intershop-pwa/intershop-pwa/node_modules/rxjs/src/internal/Subscriber.ts:113:12)
          at ThrowIfEmptySubscriber.Object.<anonymous>.Subscriber._error (/home/runner/work/intershop-pwa/intershop-pwa/node_modules/rxjs/src/internal/Subscriber.ts:143:22)
          at ThrowIfEmptySubscriber.Object.<anonymous>.Subscriber.error (/home/runner/work/intershop-pwa/intershop-pwa/node_modules/rxjs/src/internal/Subscriber.ts:113:12)
          at TakeLastSubscriber.Object.<anonymous>.Subscriber._error (/home/runner/work/intershop-pwa/intershop-pwa/node_modules/rxjs/src/internal/Subscriber.ts:143:22)
          at TakeLastSubscriber.Object.<anonymous>.Subscriber.error (/home/runner/work/intershop-pwa/intershop-pwa/node_modules/rxjs/src/internal/Subscriber.ts:113:12)
          at MergeMapSubscriber.Object.<anonymous>.OuterSubscriber.notifyError (/home/runner/work/intershop-pwa/intershop-pwa/node_modules/rxjs/src/internal/OuterSubscriber.ts:17:22)
...
```

**Comment by dhhyi** [comment]
`RouterTestingModule` in user.effects.spec must also supply this route: https://github.com/intershop/intershop-pwa/blob/75c933818976034edfaa316bc6fe1f69b2254278/src/app/core/store/user/user.effects.spec.ts#L65
